[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.5.4"
rand = "0.8.5"
ron = "0.8.1"
serde = {version = "1.0.188", features = ["derive"]}
